### ISSUE TITLE
JSON syntax error?

### ISSUE THREAD

**Issue by MikeS-nth** [singer-io/tap-salesforce#54]
Hello! I'm getting the following error when I try to run `tap-salesforce --config config.json --discover`:
`CRITICAL Expecting property name enclosed in double quotes: line 8 column 1 (char 284)`

Might be similar to Issue 20 on tap-xero: https://github.com/singer-io/tap-xero/issues/20

Details below.  I'm running tap-salesforce 1.4.17, python 3.6.5 , on Ubuntu 18.04.1 LTS 

`CRITICAL Expecting property name enclosed in double quotes: line 8 column 1 (char 284)
Traceback (most recent call last):
  File "/home/michaelsanders/.virtualenvs/tap-salesforce/bin/tap-salesforce", line 11, in <module>
    sys.exit(main())
  File "/home/michaelsanders/.virtualenvs/tap-salesforce/lib/python3.6/site-packages/tap_salesforce/__init__.py", line 387, in main
    raise e
  File "/home/michaelsanders/.virtualenvs/tap-salesforce/lib/python3.6/site-packages/tap_salesforce/__init__.py", line 378, in main
    main_impl()
  File "/home/michaelsanders/.virtualenvs/tap-salesforce/lib/python3.6/site-packages/tap_salesforce/__init__.py", line 339, in main_impl
    args = singer_utils.parse_args(REQUIRED_CONFIG_KEYS)
  File "/home/michaelsanders/.virtualenvs/tap-salesforce/lib/python3.6/site-packages/singer/utils.py", line 124, in parse_args
    args.config = load_json(args.config)
  File "/home/michaelsanders/.virtualenvs/tap-salesforce/lib/python3.6/site-packages/singer/utils.py", line 65, in load_json
    return json.load(fil)
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 8 column 1 (char 284)
(tap-salesforce) michaelsanders@ubuntu:~/singer-testing/tap-salesforce$ ^C
(tap-salesforce) michaelsanders@ubuntu:~/singer-testing/tap-salesforce$ tap-salesforce --config config.json --discover
CRITICAL Expecting property name enclosed in double quotes: line 8 column 1 (char 284)
Traceback (most recent call last):
  File "/home/michaelsanders/.virtualenvs/tap-salesforce/bin/tap-salesforce", line 11, in <module>
    sys.exit(main())
  File "/home/michaelsanders/.virtualenvs/tap-salesforce/lib/python3.6/site-packages/tap_salesforce/__init__.py", line 387, in main
    raise e
  File "/home/michaelsanders/.virtualenvs/tap-salesforce/lib/python3.6/site-packages/tap_salesforce/__init__.py", line 378, in main
    main_impl()
  File "/home/michaelsanders/.virtualenvs/tap-salesforce/lib/python3.6/site-packages/tap_salesforce/__init__.py", line 339, in main_impl
    args = singer_utils.parse_args(REQUIRED_CONFIG_KEYS)
  File "/home/michaelsanders/.virtualenvs/tap-salesforce/lib/python3.6/site-packages/singer/utils.py", line 124, in parse_args
    args.config = load_json(args.config)
  File "/home/michaelsanders/.virtualenvs/tap-salesforce/lib/python3.6/site-packages/singer/utils.py", line 65, in load_json
    return json.load(fil)
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 8 column 1 (char 284)
`

**Comment by KAllan357** [comment]
@MikeS-nth based on the stack trace, I think your config file is malformed. Can you run your config.json through a JSON linter and verify that it is correctly formatted?

https://jsonlint.com/

**Comment by MikeS-nth** [comment]
@KAllan357 thanks, you were right.  There was an extraneous comma after `true` in the last line.

FYI, that extra comma is in the example `config.json` in the readme on this repo.

Thanks.
